"""Cape materials wired to the definitive authored atlases.

Reuses the family roles (poseidon_materials.PALETTE, now including the fourth
swatch, Branco Perolado) so the set reads as one family, and follows the lane-B
material grammar: every material keeps the exact name the BMD encoder embeds as
the mesh texture (``Poseidon_{role}.jpg``) and its Base Color samples the
authored 512 JPEG atlas generated by ``generate_poseidon_atlases.py``. The Blue
energy and the Pearl gleam keep their emission accents. Nothing here installs a
texture into the client — that stays a wave-3 integration decision.

The cloth note (``cape-cloth-contract.md``): the runtime cloth grids stretch a
whole image across UV 0..1 (the ``dl_redwings02.tga`` role), so the Black mass
and the Pearl gleam atlases are authored full-field on purpose.
"""
import bpy

from poseidon_materials import PALETTE, TEXTURES, atlas_report

PEARL_COLOR = (0.824, 0.796, 0.812)  # concept swatch #CCCBD2 (linear approximation)


def create_cape_materials():
    report = atlas_report()
    result = {}
    for role, (color, metallic, roughness) in PALETTE.items():
        material = bpy.data.materials.new(f'Poseidon_{role}.jpg')
        material.use_nodes = True
        material.diffuse_color = (*color, 1)
        shader = next(node for node in material.node_tree.nodes if node.type == 'BSDF_PRINCIPLED')
        shader.inputs['Metallic'].default_value = metallic
        shader.inputs['Roughness'].default_value = roughness
        texture = material.node_tree.nodes.new('ShaderNodeTexImage')
        image = bpy.data.images.load(str(TEXTURES / f'Poseidon_{role}.jpg'))
        image.name = f'Poseidon_{role}.jpg'
        texture.image = image
        material.node_tree.links.new(texture.outputs['Color'], shader.inputs['Base Color'])
        if role in ('Blue', 'Pearl'):
            shader.inputs['Emission Strength'].default_value = 0.18 if role == 'Blue' else 0.06
            material.node_tree.links.new(texture.outputs['Color'], shader.inputs['Emission Color'])
        stats = report['atlases'][role]
        material['atlas_status'] = (
            f'DEFINITIVE: authored atlas, master sha256 {stats["master"]["sha256"][:12]}, '
            f'contrast P95-P05 {stats["game_jpeg"]["contrast_span_p95_p05"]}')
        result[role] = material
    return result
