"""Definitive Poseidon materials: the authored atlases, no provisional PBR.

Each material keeps the exact name the BMD encoder embeds as the mesh texture
(``Poseidon_{role}.jpg``), so the exported bytes and every roundtrip proof are
untouched; what changes is the shading: the Base Color (and the Blue glow)
samples the authored 512 JPEG atlas generated by ``generate_poseidon_atlases.py``
instead of a flat provisional color. Installation into the client remains an
integration decision and does not happen here.
"""
import json
from pathlib import Path

import bpy

ROOT = Path(__file__).resolve().parent
TEXTURES = ROOT / 'textures'

PALETTE = {
    'Black': ((0.023, 0.032, 0.044), 0.88, 0.23),
    'Gold': ((0.72, 0.40, 0.105), 0.84, 0.24),
    'Blue': ((0.009, 0.21, 0.48), 0.42, 0.18),
    # Branco Perolado, cape ferragem gleam; metallic/roughness carried over
    # from the provisional cape pearl (concept swatch #CCCBD2).
    'Pearl': ((0.824, 0.796, 0.812), 0.35, 0.28),
}
GLOW = {'Blue': 0.18, 'Pearl': 0.06}
DEPENDENCY_STATUS = 'AUTHORED_ATLAS_REGENERABLE'
GENERATOR = 'generate_poseidon_atlases.py'


def atlas_report():
    return json.loads((TEXTURES / 'atlas-report.json').read_text(encoding='utf-8'))


def create_materials():
    report = atlas_report()
    result = {}
    for role, (color, metallic, roughness) in PALETTE.items():
        material = bpy.data.materials.new(f'Poseidon_{role}.jpg')
        material.use_nodes = True
        material.diffuse_color = (*color, 1)
        shader = next(node for node in material.node_tree.nodes if node.type == 'BSDF_PRINCIPLED')
        shader.inputs['Metallic'].default_value = metallic
        shader.inputs['Roughness'].default_value = roughness
        texture = material.node_tree.nodes.new('ShaderNodeTexImage')
        image = bpy.data.images.load(str(TEXTURES / f'Poseidon_{role}.jpg'))
        image.name = f'Poseidon_{role}.jpg'
        texture.image = image
        material.node_tree.links.new(texture.outputs['Color'], shader.inputs['Base Color'])
        if role in GLOW:
            shader.inputs['Emission Strength'].default_value = GLOW[role]
            material.node_tree.links.new(texture.outputs['Color'], shader.inputs['Emission Color'])
        stats = report['atlases'][role]
        material['atlas_status'] = (
            f'DEFINITIVE: authored atlas, master sha256 {stats["master"]["sha256"][:12]}, '
            f'contrast P95-P05 {stats["game_jpeg"]["contrast_span_p95_p05"]}')
        result[role] = material
    return result


def atlas_dependencies():
    """The texture-dependencies.json contract: authored, regenerable, hashed."""
    report = atlas_report()
    return [dict(texture=f'Poseidon_{role}.jpg', material_role=role,
                 status=DEPENDENCY_STATUS, generator=GENERATOR,
                 linear_rgb=list(values[0]),
                 master=f'art-source/poseidon/textures/masters/Poseidon_{role}.png',
                 master_sha256=report['atlases'][role]['master']['sha256'],
                 game_jpeg_sha256=report['atlases'][role]['game_jpeg']['sha256'],
                 ozj_sha256=report['atlases'][role]['ozj']['sha256'],
                 ozj_wrapper='24 zero bytes + RGB JPEG (same contract as the Celestial atlases)')
            for role, values in PALETTE.items()]
