#pragma once

namespace UI::Voice
{
    // Interface\LuxUI\voice_mic.OZT and voice_sound.OZT, generated by
    // tools/make_hud_button_icons.py. Called from CNewUIMainFrameWindow's
    // Load/UnloadImages so the glyphs share the main HUD's texture lifetime.
    void LoadIcons();
    void UnloadIcons();

    // World-space speaking indicator (metallic glyph).
    void DrawMicrophoneIcon(float centerX, float centerY, float scale, bool enabled);

    void DrawSpeakerIcon(float centerX, float centerY, float scale, bool enabled);

    // HUD: the same glyph over the gray NewUI button.
    void DrawMicrophoneGlyph(float centerX, float centerY, float scale, bool enabled);

    void DrawSpeakerGlyph(float centerX, float centerY, float scale, bool enabled);
}
