#include "doctest.h"

#include <array>
#include <bit>
#include <cstdlib>
#include <fstream>
#include <limits>
#include <iterator>
#include <vector>
#include "Character/CharacterMovementEffects.h"
#include "Network/Server/EquipmentStatePacket.h"

namespace
{
    constexpr std::array<std::uint8_t, 16> GoldenPacket = {
        0xC1, 0x10, 0xF3, 0xE8, 0x01, 0x12, 0x34, 0x01,
        0x33, 0x33, 0x93, 0x3F, 0x6C, 0x00, 0x6C, 0x00
    };

    auto WithFactor(float factor)
    {
        auto packet = GoldenPacket;
        const auto bits = std::bit_cast<std::uint32_t>(factor);
        for (unsigned byte = 0; byte < sizeof(bits); ++byte)
            packet[8 + byte] = static_cast<std::uint8_t>(bits >> (byte * 8));
        return packet;
    }
}

TEST_CASE("Equipment state decodes the server wire contract without native struct packing")
{
    const auto update = Network::Equipment::DecodeState(GoldenPacket);
    REQUIRE(update.has_value());
    CHECK(update->CharacterId == 0x1234);
    CHECK(update->Equipment.Known);
    CHECK(update->Equipment.HasCelestialAura());
    CHECK(update->Equipment.MovementFactor == doctest::Approx(1.15f));
    CHECK(update->AttackSpeed == 108);
    CHECK(update->MagicSpeed == 108);
}

TEST_CASE("Equipment packet rejects truncated oversized and unsupported messages")
{
    for (std::size_t size = 0; size < GoldenPacket.size(); ++size)
        CHECK_FALSE(Network::Equipment::DecodeState(std::span(GoldenPacket).first(size)));
    std::array<std::uint8_t, 17> oversized{};
    std::copy(GoldenPacket.begin(), GoldenPacket.end(), oversized.begin());
    CHECK_FALSE(Network::Equipment::DecodeState(oversized));
    for (const auto offset : { 0, 1, 2, 3, 4, 7 })
    {
        auto packet = GoldenPacket;
        packet[offset] = 0xFF;
        CHECK_FALSE(Network::Equipment::DecodeState(packet));
    }
}

TEST_CASE("Equipment movement input rejects nonpositive or nonfinite values")
{
    for (float factor : { 0.0f, -1.0f, std::numeric_limits<float>::infinity(), std::numeric_limits<float>::quiet_NaN() })
        CHECK_FALSE(Network::Equipment::DecodeState(WithFactor(factor)));
}

TEST_CASE("Server movement factor includes slowdown exactly once")
{
    using namespace Character::Movement;
    const Character::Equipment::State active{ true, true, 1.15f };
    const Character::Equipment::State frozen{ true, true, 0.575f };
    CHECK(ApplyEffects(15, active, None) == doctest::Approx(17.25f));
    CHECK(ApplyEffects(12, active, None) == doctest::Approx(13.8f));
    CHECK(ApplyEffects(15, frozen, Frozen) == doctest::Approx(8.625f));
    CHECK(ApplyEffects(15, { true, true, 1.15f * 0.33f }, DestructionSlow) == doctest::Approx(5.6925f));
}

TEST_CASE("Legacy servers keep native movement effects and never infer the Celestial full set")
{
    using namespace Character::Movement;
    const Character::Equipment::State unknown;
    CHECK_FALSE(unknown.HasCelestialAura());
    CHECK(ApplyEffects(15, unknown, None) == 15);
    CHECK(ApplyEffects(15, unknown, Frozen) == doctest::Approx(7.5f));
    CHECK(ApplyEffects(15, unknown, DestructionSlow) == doctest::Approx(4.95f));
    CHECK(ApplyEffects(15, unknown, Frozen | TempleQuickness) == 20);
}

TEST_CASE("Inactive update and recycled character state remove the full-set effect")
{
    auto packet = WithFactor(1.0f);
    packet[7] = 0;
    const auto inactive = Network::Equipment::DecodeState(packet);
    REQUIRE(inactive.has_value());
    CHECK(inactive->Equipment.Known);
    CHECK_FALSE(inactive->Equipment.HasCelestialAura());
    CHECK(Character::Movement::ApplyEffects(15, inactive->Equipment, Character::Movement::None) == 15);
    auto recycled = Network::Equipment::DecodeState(GoldenPacket)->Equipment;
    recycled = {};
    CHECK_FALSE(recycled.Known);
    CHECK_FALSE(recycled.HasCelestialAura());
    CHECK(recycled.MovementFactor == 1.0f);
}

TEST_CASE("Equipment packet generated by the dotnet sender matches the client decoder")
{
    const char* fixture = std::getenv("CELESTIAL_PACKET_FIXTURE");
    if (fixture == nullptr)
    {
        MESSAGE("Set CELESTIAL_PACKET_FIXTURE to run the cross-language sender/decoder check.");
        return;
    }
    std::ifstream input(fixture, std::ios::binary);
    REQUIRE(input.good());
    const std::vector<std::uint8_t> bytes{ std::istreambuf_iterator<char>(input), {} };
    REQUIRE(bytes.size() == GoldenPacket.size());
    CHECK(std::equal(bytes.begin(), bytes.end(), GoldenPacket.begin()));
    CHECK(Network::Equipment::DecodeState(bytes).has_value());
}
